### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by talwrii** [un-def/i3-workspace-switcher#1]
Hey I wanted to fork your repository and make some tweaks. Specifically, I wanted to make it possible to install this tool with pip because that's how I like to handle my dependencies (rather than with git submodules, if possible).

I'm not sure if you are happy for me to this though since there's no license specified. Am I allowed to use your code :) - what about forking it?

Thanks

**Comment by un-def** [comment]
I've just added [LICENSE file](https://github.com/un-def/i3-workspace-switcher/blob/master/LICENSE). This code is licensed under the MIT License, feel free to fork/modify/distribute it.

**Comment by talwrii** [comment]
Thanks for that. I have a branch here that makes this repository pip installable and makes a few other changes. 

https://github.com/talwrii/i3-workspace-switcher

If you are interested in any of the changes I can make a pull request.

**Comment by un-def** [comment]
Thanks, I'll inspect your changes later and contact you for PR if I find them useful.
